export enum Regions {
    'ABRUZZO' = 'Abruzzo',
    'BASILICATA' = 'Basilicata',
    'CALABRIA' = 'Calabria',
    'CAMPANIA' = 'Campania',
    'E_ROMAGNA' = 'Emilia-Romagna',
    'F_V_G' = 'Friuli Venezia Giulia',
    'LAZIO' = 'Lazio',
    'LIGURIA' = 'Liguria',
    'LOMBARDIA' = 'Lombardia',
    'MARCHE' = 'Marche',
    'MOLISE' = 'Molise',
    'PIEMONTE' = 'Piemonte',
    'PUGLIA' = 'Puglia',
    'SARDEGNA' = 'Sardegna',
    'SICILIA' = 'Sicilia',
    'TOSCANA' = 'Toscana',
    'T_A_A_T' = 'Trentino-Alto Adige (Trento)',
    'T_A_A_B' = 'Trentino-Alto Adige (Bolzano)',
    'UMBRIA' = 'Umbria',
    'V_D_A' = "Valle d'Aosta",
    'VENETO' = 'Veneto',
}
